# Generated by Django 4.2.1 on 2023-07-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='iamge',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
